baseURL = "https://cineclubrodadebera.cat/"
languageCode = "ca"
title = "Cineclub Roda de Berà"
enableRobotsTXT = true
buildFuture = true
titleCaseStyle = "none"

[outputFormats.CARTELL]
  baseName = "cartell"
  mediaType = "text/html"
  isHTML = true

[permalinks]
  programacio = "/programacio/:year/:slug/"

[taxonomies]
  direccio = "directors"
  genere = "generes"
  interpret = "interprets"

[params]
  tagline = "Un espai per viure i compartir cinema durant tot l'any!"
  venueName = "Teatre del Casino Municipal de Roda de Berà"
  venueAddress = "Plaça dels Pins, 6, 43883 Roda de Berà (Tarragona)"
  membershipFormURL = "/fes-te-socia/#inscriu-te"
  logo = "/images/logo.png"
  instagramURL = "https://www.instagram.com/cineclub.rodadebera"
  facebookURL = "https://www.facebook.com/cineclub.rodadebera"
  contactEmail = "cineclub.rodadebera@gmail.com"

[[menu.main]]
  name = "Inici"
  url = "/"
  pageRef = "/"
  weight = 1

[[menu.main]]
  name = "Programació"
  url = "/programacio/"
  pageRef = "/programacio"
  weight = 2

[[menu.main]]
  name = "Propostes"
  url = "https://associacio.cineclubrodadebera.cat/"
  weight = 3

[[menu.main]]
  name = "Fes-te soci/a"
  url = "/fes-te-socia/"
  pageRef = "/fes-te-socia"
  weight = 4
