baseURL = "https://cineclubrodadebera.cat/"
languageCode = "ca"
title = "Cineclub Roda de Berà"
enableRobotsTXT = true

[permalinks]
  programacio = "/programacio/:year/:slug/"

[params]
  tagline = "Un espai per viure i compartir cinema durant tot l'any!"
  venueName = "Teatre del Casino Municipal de Roda de Berà"
  venueAddress = "Plaça dels Pins, 6, 43883 Roda de Berà (Tarragona)"
  membershipFormURL = "https://forms.gle/aPTySW5HKeuU712Z6"

[[menu.main]]
  name = "Inici"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Programació"
  url = "/programacio/"
  weight = 2

[[menu.main]]
  name = "Fes-te soci/a"
  url = "/fes-te-socia/"
  weight = 3

[[menu.main]]
  name = "Preguntes freqüents"
  url = "/preguntes-frequents/"
  weight = 4
